-- Copyright (c) 2020-2021 shadmansaleh
-- MIT license, see LICENSE for more details.
-- Generated by lightline to lualine theme converter
-- https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9
-- stylua: ignore
local colors = {
  text     = '#cdd6f4',
  color2   = '#0f1419',
  color3   = '#bac2de',
  color4   = '#e6e1cf',
  color5   = '#14191f',
  color13  = '#313244',
  color10  = '#6c7086',
  color8   = '#f5c2e7',
  color9   = '#3e4b59',
  surface2 = '#585b70',
  surface1 = '#45475a',
  surface0 = '#313244',
  base     = '#1e1e2e',
  mantle   = '#181825',
  crust    = '#11111b',

}

return {
  command = {
    a = { fg = colors.color10, bg = colors.surface0, gui = 'bold' },
    b = { fg = colors.text, bg = colors.color5 },
    c = { fg = colors.text, bg = colors.color2 },
    y = { fg = colors.color10, bg = colors.base },
  },
  insert = {
    a = { fg = colors.text, bg = colors.color13, gui = 'bold' },
    b = { fg = colors.text, bg = colors.color5 },
    c = { fg = colors.text, bg = colors.crust },
    x = { fg = colors.text, bg = colors.crust },
    y = { fg = colors.color10, bg = colors.mantle },
  },
  normal = {
    a = { fg = colors.color5, bg = colors.color10, gui = 'bold' },
    b = { fg = colors.text, bg = colors.color5 },
    c = { fg = colors.text, bg = colors.color2 },
    y = { fg = colors.color10, bg = colors.base },
  },
  visual = {
    a = { fg = colors.color2, bg = colors.color3, gui = 'bold' },
    b = { fg = colors.color4, bg = colors.color5 },
    y = { fg = colors.color10, bg = colors.base },
  },
  replace = {
    a = { fg = colors.color2, bg = colors.color8, gui = 'bold' },
    b = { fg = colors.color4, bg = colors.color5 },
    y = { fg = colors.color10, bg = colors.base },
  },
  inactive = {
    c = { fg = colors.color4, bg = colors.color2 },
    a = { fg = colors.color4, bg = colors.color5, gui = 'bold' },
    b = { fg = colors.color4, bg = colors.color5 },
    y = { fg = colors.color10, bg = colors.base },
  },
}
