# only this line might not be enough
set -g default-terminal "tmux-256color"

#Needs this line also to override the default color
set -sag terminal-features ",*:RGB"
set -sag terminal-features ",*:usstyle"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -g status-position top

# Reset Leader Prefix
# unbind C-b
# set -g prefix C-a
# bind-key C-a send-prefix

# =============================
# New Leader Prefix Bindings
# =============================

# Unbind the default prefix
unbind C-b

# Set prefix to Ctrl+Space
set-option -g prefix C-Space

# Bind Ctrl+Space as a shortcut
bind C-Space send-prefix

# Reload Config Binding
unbind r
# reload config file
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"

# Window Split Bindings
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# Resize Panes Bindings
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Maximize Split with <prefix> + m
bind -r m resize-pane -Z

set -g mouse on

# ===========
# TPM Plugins
# ===========
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# TMUX Continuum Settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval 5

# ===========
# Weather
# ===========

set-option -g @tmux-weather-units "u"
set-option -g @tmux-weather-location "78501"

# ================
# Catppuccin Theme
# ================


set -g @catppuccin_directory_text "#(~/.bin/shorten_path.sh '#{pane_current_path}')"

set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

# Minimize left and right status padding
set -g status-left "#{E:@catppuccin_status_user} | #{E:@catppuccin_status_host}"
# set -g status-right "#{E:@catppuccin_status_directory} #{E:@catppuccin_status_host} #{E:@catppuccin_status_session}"
# set -g status-right "#{E:@catppuccin_status_directory} #{E:@catppuccin_status_session} #{weather}"
set -g @catppuccin_date_time_text "%a %b %d - %I:%M%p"
set -g status-right "#{E:@catppuccin_status_date_time} | #{E:@catppuccin_status_directory} #{E:@catppuccin_status_session} #{weather}"

# Ensure alignment is set to left
set -g status-justify left

# Limit status bar lengths to reduce empty space
set -g status-left-length 40
set -g status-right-length 200

# bootstrap tpm
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
